# Generated by Django 4.1 on 2022-08-10 16:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('email_id', models.EmailField(max_length=255, unique=True)),
                ('accound_name', models.CharField(max_length=255)),
                ('account_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('http', models.CharField(max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
            ],
        ),
        migrations.CreateModel(
            name='Headers',
            fields=[
                ('app_id', models.CharField(max_length=255)),
                ('app_secret', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('content_type', models.CharField(default='application/json', max_length=255)),
                ('accept', models.CharField(default='*', max_length=255)),
                ('destination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.destination')),
            ],
        ),
    ]
