# Generated by Django 4.1 on 2022-08-11 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_datahandler'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='app_secret_token',
            field=models.CharField(default='zaR9KADKri1lkCQONCaNI2aDbTz7rRsL', max_length=255),
        ),
    ]
