# Generated by Django 4.1 on 2022-08-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_account_app_secret_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='app_secret_token',
            field=models.CharField(default='S8hP95H18vegC8vs19AKhrqqmMw3LypD', max_length=255, unique=True),
        ),
    ]
