# Generated by Django 4.1 on 2022-08-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_account_app_secret_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='app_secret_token',
            field=models.CharField(default='hjyuNkzgB8H1r7iuTwl9T5rwJyXUgMtp', max_length=255, unique=True),
        ),
    ]
